### PR TITLE
[Merged by Bors] - feat: Set explicit resources on all containers

### PR DESCRIPTION
**Pull request by razvan**
Part of: https://github.com/stackabletech/issues/issues/394

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [x] Feature Tracker has been updated
- [x] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by razvan** [comment]
One unrelated test failed on `kind` (with **zookeeper=0.0.0-pr691** and **hdfs=0.0.0-pr359**):

```
    --- FAIL: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (213.85s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (232.32s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (194.32s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (204.19s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (185.15s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (203.79s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (186.88s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (209.27s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (193.86s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (211.46s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (178.43s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (187.05s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (184.82s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (183.73s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (194.66s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (190.66s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (201.62s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (195.40s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (200.78s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (198.85s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (182.71s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (194.37s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (215.50s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (200.58s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (191.22s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (195.03s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (179.70s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (182.70s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (182.31s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (189.00s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.11-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (207.66s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (179.90s)
        --- PASS: kuttl/harness/logging_hbase-2.4.8-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (196.31s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (194.48s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (186.98s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.9-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (202.11s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (206.51s)
        --- PASS: kuttl/harness/logging_hbase-2.4.11-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (178.55s)
        --- PASS: kuttl/harness/logging_hbase-2.4.12-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (156.11s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (222.81s)
        --- PASS: kuttl/harness/logging_hbase-2.4.9-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (188.09s)
        --- PASS: kuttl/harness/resources_hbase-latest-2.4.12-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (175.13s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-cluster-internal (208.96s)
        --- FAIL: kuttl/harness/cluster-operation_hbase-latest-2.4.12-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (362.29s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (182.52s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (211.10s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-external-unstable (194.27s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.7.0-stackable0.0.0-dev_listener-class-cluster-internal (189.58s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-external-unstable (198.26s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (193.74s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.2.2-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (187.20s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.8-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.6.3-stackable0.0.0-dev_listener-class-cluster-internal (198.66s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.12-stackable0.0.0-dev_hdfs-3.3.3-stackable0.0.0-dev_zookeeper-3.8.0-stackable0.0.0-dev_listener-class-external-unstable (218.46s)
        --- PASS: kuttl/harness/orphaned_resources_hbase-latest-2.4.12-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (170.82s)
        -
```

**Comment by razvan** [comment]
After two more attempts the previously failed test, succeeded:

```
--- PASS: kuttl (156.74s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/cluster-operation_hbase-latest-2.4.12-stackable0.0.0-dev_hdfs-latest-3.3.4-stackable0.0.0-dev_zookeeper-latest-3.8.0-stackable0.0.0-dev (156.71s)
```

**Review by sbernauer — CHANGES_REQUESTED** [review]
LGTM. Do we have a `create-tls-cert-bundle` container? If yes please add resources, if not pls remove from gsheet

**Comment by maltesander** [comment]
> LGTM. Do we have a `create-tls-cert-bundle` container? If yes please add resources, if not pls remove from gsheet

removed it from sheets!

**Review by sbernauer — APPROVED** [review]
Thx!

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
