### PR TITLE
feat: run containerdebug in the background

### PR DESCRIPTION
**Pull request by razvan**
# Description

Part of: https://github.com/stackabletech/issues/issues/527

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Comment by nightkr** [comment]
Looks like the `smoke` tests now fails on step 60 (phoenix) because the restserver gets OOMKilled and then doesn't have the `/tmp/test_phoenix.sh` script anymore. After increasing the restserver memory budget to 1GiB it _still_ seems to fail for some unclear reason, but only when running _without_ `--skip-delete`.

**Comment by razvan** [comment]
:green_circle: CI https://testing.stackable.tech/job/hbase-operator-it-custom/41/

**Comment by nightkr** [comment]
Tests pass for me if I up the resource limits:

```diff
diff --git a/tests/templates/kuttl/kerberos/30-install-hbase.yaml.j2 b/tests/templates/kuttl/kerberos/30-install-hbase.yaml.j2
index f862651..31a27a6 100644
--- a/tests/templates/kuttl/kerberos/30-install-hbase.yaml.j2
+++ b/tests/templates/kuttl/kerberos/30-install-hbase.yaml.j2
@@ -39,6 +39,9 @@ commands:
           config:
             logging:
               enableVectorAgent: {{ lookup('env', 'VECTOR_AGGREGATOR') | length > 0 }}
+            resources:
+              memory:
+                limit: 1536Mi
           roleGroups:
             default:
               replicas: 2
diff --git a/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2 b/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
index ac1bed8..53e9a98 100644
--- a/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
+++ b/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
@@ -45,6 +45,9 @@ spec:
     config:
       logging:
         enableVectorAgent: {{ lookup('env', 'VECTOR_AGGREGATOR') | length > 0 }}
+      resources:
+        memory:
+          limit: 1Gi
     roleGroups:
       default:
         configOverrides:
```

But that's pretty concerning to me, is that indicative of a larger problem with our default resource limits here?

**Comment by razvan** [comment]
Thanks, [applied](https://github.com/stackabletech/hbase-operator/pull/605/commits/d2252b2f0ce73e4e4842f38b51bdf0399095687a).

**Review by nightkr — APPROVED** [review]

**Pull request merged**
